<a href="https://colab.research.google.com/github/PedroGonzalezBeermann2020/QM206-2024/blob/main/Clase03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array([3,5,2,7,6,5,9])
x

array([3, 5, 2, 7, 6, 5, 9])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[2,:]

array([7, 8, 9])

In [ ]:
print(x)
print(x*x)
print(np.sum(x))
print(np.sum(x*x))

[3 5 2 7 6 5 9]
[ 9 25  4 49 36 25 81]
37
229


In [ ]:
x=np.array([3.4,6.5,8.3,2.4,7.8])
n=len(x)
prom=np.sum(x)/n
print("promedio=",prom)
s2=np.sum((x-prom)**2)/(n-1)
print("varianza=",s2)
des=np.sqrt(s2)
print("desviacion estandar=",des)

promedio= 5.680000000000001
varianza= 6.997000000000002
desviacion estandar= 2.6451843035977665


In [ ]:
x=np.array([3.4,6.5,8.3,2.4,7.8])
y=np.array([4.6,3.2,7.8,9.2,3.5])
sumxy=np.sum(x*y)
sumxy2=np.sum(x*y*y)
print("sumXY=",sumxy)
print("sumXY2=",sumxy2)

sumXY= 150.56
sumXY2= 942.1619999999999


In [ ]:
m=np.sum(x*x)/np.sum(x*y)
print("m=",m)

m= 1.25730605738576


In [ ]:
x=np.array([1,2,3,4,5,6])
print(np.cumsum(x))

[ 1  3  6 10 15 21]


In [ ]:
print(np.cumprod(x))

[  1   2   6  24 120 720]


In [ ]:
ka=np.array([2.5E-3,5.4E-6,8.9E-9])
kt=np.cumprod(ka)
print(kt)

[2.5000e-03 1.3500e-08 1.2015e-16]


In [ ]:
pKa=np.array([1.25,4.26])
Ka=10**(-pKa)
print(Ka)
Kat=np.cumprod(Ka)
print(Kat)

[5.62341325e-02 5.49540874e-05]
[5.62341325e-02 3.09029543e-06]


In [ ]:
x=np.random.rand(10)
print(np.sum(x))

3.643475925470153


In [ ]:
n=np.random.randint(14,size=50)
print(n)

[13  2 13 11  7 12  0  6 12 12 10  8 10 13  6  3 10  8 12 11  6  1  7  5
 10  8  0  5 12  5 13  4  1  3  6  0  4  8  3  1  9  6  5  8  2  7 13  2
 12  7]


In [75]:
pH=5.0
H=10**(-pH)
n=np.array([2,1,0])
a=H**n
print(a)

pKa=np.array([1.25,4.26])
Ka=10**(-pKa)
Ka=np.append(1,Ka)
Kat=np.cumprod(Ka)
print(Kat)
v=np.sum(Kat*a)
print("v=",v)

[1.e-10 1.e-05 1.e+00]
[1.00000000e+00 5.62341325e-02 3.09029543e-06]
v= 3.6527367577039416e-06
