<a href="https://colab.research.google.com/github/PedroGonzalezBeermann2020/QM206-2024/blob/main/Clase02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
18 % 4

2

In [7]:
print(3**3)
print(3**(-5))
print(3E-5)

27
0.00411522633744856
3e-05


In [10]:
x=5
print(x)
x+=3
print(x)
x-=4
print(x)


5
8
4


In [12]:
x=4
x*=6
print(x)
x=4
x=x*6
print(x)

24
24


In [13]:
x=7
x%=5
print(x)

2


In [14]:
x=9
x//=2
print(x)

4


In [15]:
x=5
x**=3
print(x)

125


In [17]:
x=5
a=x**3
print(a)
print(x)

125
5


In [18]:
thislist = ["apple", "banana", "cherry"]
print(len(thislist))

3


In [21]:
est1=["Juan Perez",22,1.70,"Negro","Química","Unachi"]
print(est1[3])
print(type(est1))


Negro
<class 'list'>


In [23]:
datos=("apple", "banana", "cherry")
print(type(datos))
thislist = list(datos)
print(type(thislist))

<class 'tuple'>
<class 'list'>


In [31]:
estudiantes=["Juan","Pedro","Jose"]
print(estudiantes)
estudiantes.append("María")
print(estudiantes)
estudiantes.insert(2,"Luis")
print(estudiantes)
profesores=["Viviana","Dayli","Dixon","Juan"]
estudiantes.extend(profesores)
print(estudiantes)
estudiantes.remove("Dixon")
print(estudiantes)
estudiantes.remove("Juan")
print(estudiantes)

['Juan', 'Pedro', 'Jose']
['Juan', 'Pedro', 'Jose', 'María']
['Juan', 'Pedro', 'Luis', 'Jose', 'María']
['Juan', 'Pedro', 'Luis', 'Jose', 'María', 'Viviana', 'Dayli', 'Dixon', 'Juan']
['Juan', 'Pedro', 'Luis', 'Jose', 'María', 'Viviana', 'Dayli', 'Juan']
['Pedro', 'Luis', 'Jose', 'María', 'Viviana', 'Dayli', 'Juan']


In [7]:
thislist = ["apple", "banana", "cherry"]
print(thislist)
for x in thislist:
  print("I like",x)
  print("Voy a comprar 2 lbs de ",x)
print("se ha terminado la lista de las frutas")

['apple', 'banana', 'cherry']
I like apple
Voy a comprar 2 lbs de  apple
I like banana
Voy a comprar 2 lbs de  banana
I like cherry
Voy a comprar 2 lbs de  cherry
se ha terminado la lista de las frutas


In [13]:
xs=[5,3,7,6,4]
v=2
for a in xs:
  b=a*5
  c=a**2
  print(b,c)
  v+=3
  print(v)
print("v=",v)

25 25
5
15 9
8
35 49
11
30 36
14
20 16
17
v= 17


In [21]:
notas=[3.7]
suma=0
n=len(notas)
for x in notas:
  suma+=x
print("suma=",suma)
if n!=0:
  promedio=suma/n
  print("promedio=",promedio)
else:
  print("no hay notas")

suma= 3.7
promedio= 3.7


$ x=\frac{-b + \sqrt{b*b-4*a*c}}{2a} $

$ ax^2+bx+c=0 $

In [26]:
a=3
b=6
c=-1
if 4*a*c<b**2:
  x1=(-b+(b**2-4*a*c)**0.5)/(2*a)
  x2=(-b-(b**2-4*a*c)**0.5)/(2*a)
  print("x1=",x1)
  print("x2=",x2)
else:
  print("no hay raices reales")

x1= 0.15470053837925146
x2= -2.1547005383792515


In [30]:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort(reverse = True)
print(thislist)

['pineapple', 'orange', 'mango', 'kiwi', 'banana']


In [33]:
thislist = ["apple", "banana", "cherry"]
mylist = thislist.copy()
mylist[0]="orange"
print(thislist)
print(mylist)

['apple', 'banana', 'cherry']
['orange', 'banana', 'cherry']


In [34]:
thislist = ["apple", "banana", "cherry"]
mylist = thislist
mylist[0]="orange"
print(thislist)
print(mylist)

['orange', 'banana', 'cherry']
['orange', 'banana', 'cherry']


In [36]:
list1 = ["a", "b", "c"]
list2 = [1, 2, 3]

list3 = list1 + list2+list1
print(list3)

['a', 'b', 'c', 1, 2, 3, 'a', 'b', 'c']


In [46]:
fruits = ['cherry','apple','mango', 'banana', 'cherry']

x = fruits.count("cherry")
print(x)
n=fruits.index("cherry")
print(n)

2
0


In [48]:
import numpy as np

x=8.7
s=np.sqrt(x)
print(s)
v=np.exp(x)
print(v)


2.949576240750525
6002.912217261018


In [53]:
x=np.array([0.0,3.4,6.7,8.9,2.6,-3.5])
for a in x:
  print(a,np.exp(a))

0.0 1.0
3.4 29.96410004739701
6.7 812.4058251675433
8.9 7331.973539155995
2.6 13.463738035001692
-3.5 0.0301973834223185


In [57]:
x=np.zeros(10)
print(x)
x[3]=5
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]


In [64]:
v=np.ones(200)
v=v+3
print(v*v)

[16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.
 16. 16.]


In [79]:
x=np.linspace(1, 5,5)
y=3.0*np.exp(-x/5)


print(np.sum(x))
print(np.mean(x))
print(np.log(x))
print(np.log10(x))

15.0
3.0
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [80]:
cH=np.array([1.5E-4,6.7E-7,8.9E-2])
pH=-np.log10(cH)
print(pH)

[3.82390874 6.1739252  1.05060999]
