<a href="https://colab.research.google.com/github/PedroGonzalezBeermann2020/QM206-2024/blob/main/Clase03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
x=np.array([3,5,2,7,6,5,9])
x

array([3, 5, 2, 7, 6, 5, 9])

In [ ]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z[2,:]

array([7, 8, 9])

In [ ]:
print(x)
print(x*x)
print(np.sum(x))
print(np.sum(x*x))

[3 5 2 7 6 5 9]
[ 9 25  4 49 36 25 81]
37
229


In [ ]:
x=np.array([3.4,6.5,8.3,2.4,7.8])
n=len(x)
prom=np.sum(x)/n
print("promedio=",prom)
s2=np.sum((x-prom)**2)/(n-1)
print("varianza=",s2)
des=np.sqrt(s2)
print("desviacion estandar=",des)

promedio= 5.680000000000001
varianza= 6.997000000000002
desviacion estandar= 2.6451843035977665


In [ ]:
x=np.array([3.4,6.5,8.3,2.4,7.8])
y=np.array([4.6,3.2,7.8,9.2,3.5])
sumxy=np.sum(x*y)
sumxy2=np.sum(x*y*y)
print("sumXY=",sumxy)
print("sumXY2=",sumxy2)

sumXY= 150.56
sumXY2= 942.1619999999999


In [ ]:
m=np.sum(x*x)/np.sum(x*y)
print("m=",m)

m= 1.25730605738576


In [ ]:
x=np.array([1,2,3,4,5,6])
print(np.cumsum(x))

[ 1  3  6 10 15 21]


In [ ]:
print(np.cumprod(x))

[  1   2   6  24 120 720]


In [ ]:
ka=np.array([2.5E-3,5.4E-6,8.9E-9])
kt=np.cumprod(ka)
print(kt)

[2.5000e-03 1.3500e-08 1.2015e-16]


In [ ]:
pKa=np.array([1.25,4.26])
Ka=10**(-pKa)
print(Ka)
Kat=np.cumprod(Ka)
print(Kat)

[5.62341325e-02 5.49540874e-05]
[5.62341325e-02 3.09029543e-06]


In [ ]:
x=np.random.rand(10)
print(np.sum(x))

3.643475925470153


In [ ]:
n=np.random.randint(14,size=50)
print(n)

[13  2 13 11  7 12  0  6 12 12 10  8 10 13  6  3 10  8 12 11  6  1  7  5
 10  8  0  5 12  5 13  4  1  3  6  0  4  8  3  1  9  6  5  8  2  7 13  2
 12  7]


In [10]:
pH=8.5
H=10**(-pH)
n=np.array([2,1,0])
a=H**n
print(a)

pKa=np.array([3.25,7.26])
Ka=10**(-pKa)
Ka=np.append(1,Ka)
Kat=np.cumprod(Ka)
print(Kat)
sumTotal=np.sum(Kat*a)
print("sumTotal=",sumTotal)
frac=(Kat*a)/sumTotal
print(frac)

[1.00000000e-17 3.16227766e-09 1.00000000e+00]
[1.00000000e+00 5.62341325e-04 3.09029543e-11]
sumTotal= 3.268124373517484e-11
[3.05985907e-07 5.44128438e-02 9.45586850e-01]


In [29]:
pHs=np.arange(1,14,0.5)
for pH in pHs:
  H=10**(-pH)
  n=np.array([3,2,1,0])
  a=H**n
  pKa=np.array([2.15,7.2,12.15])
  Ka=10**(-pKa)
  Ka=np.append(1,Ka)
  Kat=np.cumprod(Ka)
  sumTotal=np.sum(Kat*a)
  frac=(Kat*a)/sumTotal
  print(pH,frac)

1.0 [9.33885900e-01 6.61140586e-02 4.17151508e-08 2.95320652e-19]
1.5 [8.17078536e-01 1.82921099e-01 3.64975576e-07 8.17078536e-18]
2.0 [5.85497147e-01 4.14500237e-01 2.61531969e-06 1.85150455e-16]
2.5 [3.08759589e-01 6.91226619e-01 1.37917842e-05 3.08759589e-15]
3.0 [1.23763839e-01 8.76180878e-01 5.52832760e-05 3.91375622e-14]
3.5 [4.27502461e-02 9.57058796e-01 1.90958335e-04 4.27502461e-13]
4.0 [1.39199678e-02 9.85458250e-01 6.21782121e-04 4.40188031e-12]
4.5 [4.43815612e-03 9.93579392e-01 1.98245152e-03 4.43815612e-11]
5.0 [1.40171336e-03 9.92337063e-01 6.26122358e-03 4.43260684e-10]
5.5 [4.37753718e-04 9.80008502e-01 1.95537403e-02 4.37753718e-09]
6.0 [1.32852553e-04 9.40524050e-01 5.93430557e-02 4.20116661e-08]
6.5 [3.72369341e-05 8.33631116e-01 1.66331275e-01 3.72369341e-07]
7.0 [8.66068906e-06 6.13129831e-01 3.86858770e-01 2.73875035e-06]
7.5 [1.49127595e-06 3.33855099e-01 6.66128497e-01 1.49127595e-05]
8.0 [1.93233021e-07 1.36798502e-01 8.63140199e-01 6.11056465e-05]
8.5 [2.131

In [14]:
pHs

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5])

FUNCIONES

In [21]:
def func1(x,z):
  y=x**2+5*z
  return y


In [23]:
a=func1(8,2)
print(a)

74


In [35]:
def fracCalc(pKa,pH):
  na=len(pKa)
  Ka=10**(-pKa)
  Ka=np.append(1,Ka)
  Kat=np.cumprod(Ka)
  n=np.arange(na,-1,-1)
  H=10**(-pH)
  a=H**n
  sumTotal=np.sum(Kat*a)
  frac=(Kat*a)/sumTotal
  return frac

In [41]:
pKas=np.array([4.72,8.0,12.0])
pHs=np.arange(1,14,0.5)
for pH in pHs:
    print(fracCalc(pKas,pH))

[9.99809490e-01 1.90509771e-04 1.90509771e-11 1.90509771e-22]
[9.99397803e-01 6.02196727e-04 1.90431326e-10 6.02196727e-21]
[9.98098161e-01 1.90183684e-03 1.90183684e-09 1.90183684e-19]
[9.94010476e-01 5.98950541e-03 1.89404791e-08 5.98950541e-18]
[9.81301498e-01 1.86983146e-02 1.86983146e-07 1.86983146e-16]
[9.43166784e-01 5.68314187e-02 1.79716726e-06 5.68314187e-15]
[8.39937251e-01 1.60046744e-01 1.60046744e-05 1.60046744e-13]
[6.23927573e-01 3.75953540e-01 1.18886948e-04 3.75953540e-12]
[3.43953922e-01 6.55390687e-01 6.55390687e-04 6.55390687e-11]
[1.41951684e-01 8.55343481e-01 2.70483358e-03 8.55343481e-10]
[4.93945380e-02 9.41193517e-01 9.41193517e-03 9.41193517e-09]
[1.58324483e-02 9.53999348e-01 3.01681083e-02 9.53999348e-08]
[4.74831848e-03 9.04773433e-01 9.04773433e-02 9.04773433e-07]
[1.25926872e-03 7.58784436e-01 2.39948707e-01 7.58784436e-06]
[2.62321780e-04 4.99843847e-01 4.99843847e-01 4.99843847e-05]
[3.98609195e-05 2.40185791e-01 7.59534162e-01 2.40185791e-04]
[4.76662

In [31]:
na=3
np.arange(na,-1,-1)

array([3, 2, 1, 0])